#!/usr/bin/env bash
#
# generate-secrets.sh — generate a Swift `Secrets` enum from a `.env` file.
#
# ---------------------------------------------------------------------------
# USAGE
# ---------------------------------------------------------------------------
#
#   generate-secrets.sh <env-file> <output-file>
#
# As an Xcode Run Script Build Phase, placed *before* Compile Sources:
#
#   "${SRCROOT}/Scripts/generate-secrets.sh" \
#       "${SRCROOT}/Config/.env.${TARGET_NAME}" \
#       "${DERIVED_FILE_DIR}/Secrets.swift"
#
# The same invocation works unchanged in CI under `xcodebuild`, since it only
# relies on environment variables Xcode sets in both cases.
#
# ---------------------------------------------------------------------------
# SANDBOXING
# ---------------------------------------------------------------------------
#
# This script's paths come from Xcode environment variables ($SRCROOT,
# $DERIVED_FILE_DIR), so Xcode cannot statically determine which files the
# phase reads and writes. With `ENABLE_USER_SCRIPT_SANDBOXING = YES` (the
# default for new projects) the phase will then fail with "Operation not
# permitted". Pick one of:
#
#   1. (Recommended) In the build phase, uncheck
#      "Based on command line arguments" (under the sandboxing / dependency
#      analysis options). Xcode stops trying to infer paths and the phase runs
#      with the normal build sandbox.
#
#   2. Declare the paths yourself, as Input/Output Files or File Lists:
#
#        Input Files:   $(SRCROOT)/Config/.env.$(TARGET_NAME)
#        Output Files:  $(DERIVED_FILE_DIR)/Secrets.swift
#
#      Listing the output gives Xcode correct dependency analysis and build
#      ordering. It does NOT add the file to Compile Sources — output files are
#      only build-system metadata. The generated file must be declared as a
#      source of the target separately (see GETTING COMPILED, below).
#
#      Note: this script writes "<output>.tmp" alongside the output before
#      renaming it into place. If the sandbox rejects that undeclared write,
#      declare the .tmp path as a second Output File. Do not relocate it to
#      $TMPDIR — a different filesystem turns the atomic rename into a
#      copy-then-unlink and loses the guarantee described below.
#
# ---------------------------------------------------------------------------
# GETTING COMPILED
# ---------------------------------------------------------------------------
#
# A file under $DERIVED_FILE_DIR cannot be referenced from project.yml: the
# path varies per configuration and does not exist at generation time. So when
# the project is generated by XcodeGen, write the output into the source tree
# instead and declare it on the target:
#
#     "${SRCROOT}/Scripts/generate-secrets.sh" \
#         "${SRCROOT}/Config/.env.${TARGET_NAME}" \
#         "${SRCROOT}/Generated/Secrets.swift"
#
#     # project.yml
#     targets:
#       MyApp:
#         sources:
#           - path: Sources
#           - path: Generated/Secrets.swift
#             optional: true      # absent on a fresh clone; it is gitignored
#
# `optional` applies to files, not directories — point at the file itself.
# The run script phase must still sit above Compile Sources, or the compiler
# reads a stale file (or none at all, on a clean checkout).
#
# Writing into $SRCROOT rather than the build directory has two consequences:
# user script sandboxing is far more likely to reject it (see above), and
# Xcode's change detection for outputs inside $SRCROOT is unreliable, so keep
# "Based on dependency analysis" unchecked and let the cmp check below decide.
#
# ---------------------------------------------------------------------------
# CONVENTIONS (.env syntax)
# ---------------------------------------------------------------------------
#
# One `KEY=value` per line. Blank lines and lines starting with `#` are
# skipped. Keys are converted from SNAKE_CASE to camelCase:
#
#     API_BASE_URL=…            ->  static let apiBaseUrl = …
#
# Quoted values become Swift string literals; unquoted values are emitted
# verbatim, so numbers, booleans and identifiers keep their inferred type:
#
#     API_KEY="abc123"          ->  static let apiKey = "abc123"
#     MAX_RETRY_COUNT=3         ->  static let maxRetryCount = 3
#     ENABLE_LOGGING=true       ->  static let enableLogging = true
#
# `|# ` introduces a trailing comment, rendered as a Swift `//` comment:
#
#     API_KEY="abc" |# rotate   ->  static let apiKey = "abc" // rotate
#
# Comma-separated values become an array, one element per line, each with its
# own optional comment:
#
#     PATHS="a.cer" |# first, "b.cer" |# second
#
#         static let paths = [
#             "a.cer", // first
#             "b.cer", // second
#         ]
#
# Only commas *outside* quotes split a list, so a comma inside a string is
# just a character — `GREETING="Hello, neighbours"` is a scalar. Escaped
# quotes are understood too: `QUOTE="He said \"hello, world\""` is a single
# string. Quote characters inside a `|#` comment are treated as prose, so
# apostrophes are safe: `PATHS="a" |# don't rotate, "b" |# ok` still splits.
#
# The one thing to avoid is a comma inside a comment. It is indistinguishable
# from a list separator (`"a" |# c1, "b"` has exactly that shape), so it splits
# the value. That cannot be detected directly, but its effect can: every list
# element must be a valid Swift literal and all elements must be of the same
# kind (string / number / bool / identifier), since Swift arrays are homogeneous.
# A violation aborts the build with a clickable
#     <env-file>:<line>: error: …
# rather than emitting Swift that fails to compile. The trade-off: a
# deliberately mixed list such as `1.5, CGFloat.pi` is rejected too — write
# every element in the same form.
#
# ---------------------------------------------------------------------------

set -euo pipefail

usage() {
    echo "usage: $(basename "$0") <env-file> <output-file>" >&2
    echo "  e.g. $(basename "$0") Config/.env.MyApp Generated/Secrets.swift" >&2
}

if [[ $# -ne 2 ]]; then
    echo "error: expected 2 arguments, got $#" >&2
    usage
    exit 1
fi

ENV_FILE="$1"
OUT="$2"

if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: env file not found: $ENV_FILE" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"

TMP="$OUT.tmp"
trap 'rm -f "$TMP"' EXIT

# ---------------------------------------------------------------------------
# read_key: turn a single `KEY=value` line into Swift source on stdout.
# ---------------------------------------------------------------------------

AWK_READ_KEY=$(cat <<'AWK'
# Split `s` on commas that are not inside quotes. Returns the element count.
# Backslash escapes the following character while inside a quoted section.
# Once an unquoted `|#` is seen, the rest of the element is comment text: quote
# characters there are prose (apostrophes, quoted words) and must not open a
# quoted section, or every later comma would look quoted and the list would
# never split. Only a comma ends the comment and starts the next element.
function unquoted_split(s, arr,   i, n, c, q, cur, len, inc) {
    n = 0; q = ""; cur = ""; len = length(s); inc = 0
    for (i = 1; i <= len; i++) {
        c = substr(s, i, 1)
        if (inc) {
            if (c == ",") { arr[++n] = cur; cur = ""; inc = 0; continue }
            cur = cur c
            continue
        }
        if (q != "" && c == "\\" && i < len) {
            cur = cur c substr(s, i + 1, 1)
            i++
            continue
        }
        if (q == "" && substr(s, i, 2) == "|#") {
            inc = 1
            cur = cur "|#"
            i++
            continue
        }
        if (c == "\"" || c == "'") {
            if (q == "") q = c
            else if (q == c) q = ""
            cur = cur c
            continue
        }
        if (c == "," && q == "") {
            arr[++n] = cur
            cur = ""
            continue
        }
        cur = cur c
    }
    arr[++n] = cur
    return n
}

# 1 if `s` contains a comma outside of quotes, 0 otherwise.
function has_unquoted_comma(s,   parts) {
    return (unquoted_split(s, parts) > 1)
}

# Position of `needle` in `s` outside of quotes, or 0.
function unquoted_index(s, needle,   i, c, q, len, nlen) {
    q = ""; len = length(s); nlen = length(needle)
    for (i = 1; i <= len; i++) {
        c = substr(s, i, 1)
        if (q != "" && c == "\\" && i < len) { i++; continue }
        if (c == "\"" || c == "'") {
            if (q == "") q = c
            else if (q == c) q = ""
            continue
        }
        if (q == "" && substr(s, i, nlen) == needle) return i
    }
    return 0
}

function trim(s) {
    gsub(/^[ \t\r]+|[ \t\r]+$/, "", s)
    return s
}

# Resolve .env-level escapes, then escape for a Swift string literal.
function swift_escape(s,   i, c, nxt, out, len) {
    out = ""; len = length(s)
    for (i = 1; i <= len; i++) {
        c = substr(s, i, 1)
        if (c == "\\" && i < len) {
            nxt = substr(s, i + 1, 1)
            if (nxt == "\"" || nxt == "'" || nxt == "\\") {
                c = nxt
                i++
            }
        }
        if (c == "\\")          out = out "\\\\"
        else if (c == "\"")     out = out "\\\""
        else if (c == "\t")     out = out "\\t"
        else                    out = out c
    }
    return out
}

# Shared value handling for both the scalar and the list path:
# pulls off any `|#` comment (into the global `last_comment`), trims, and
# either returns a quoted Swift string literal or the raw value verbatim.
# An empty value returns "".
function process_value(v,   idx, first, last) {
    last_comment = ""
    idx = unquoted_index(v, "|#")
    if (idx > 0) {
        last_comment = trim(substr(v, idx + 2))
        v = substr(v, 1, idx - 1)
    }
    v = trim(v)
    if (v == "") return ""
    first = substr(v, 1, 1)
    last = substr(v, length(v), 1)
    if (length(v) >= 2 && ((first == "\"" && last == "\"") || (first == "'" && last == "'")))
        return "\"" swift_escape(substr(v, 2, length(v) - 2)) "\""
    return v
}

# Report a problem in Xcode's "<file>:<line>: error: <msg>" format so it is
# clickable in the build log, and abort — a partially written Secrets.swift is
# worse than no build. The caller discards the .tmp file, so $OUT is untouched.
function fail(sk, msg) {
    printf "%s:%s: error: %s (key %s)\n", ENVIRON["ENV_FILE"], ENVIRON["ENV_LINENO"], msg, sk \
        > "/dev/stderr"
    exit 2
}

# Classify an already-processed value so list elements can be checked for
# consistency. Swift arrays are homogeneous, so a mixed list is always a bug.
function classify(v) {
    if (substr(v, 1, 1) == "\"")                     return "string"
    if (v ~ /^-?[0-9]+(\.[0-9]+)?$/)                  return "number"
    if (v == "true" || v == "false")                 return "bool"
    if (v ~ /^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$/) return "ident"
    return "invalid"
}

function read_scalar_key(sk, rest,   val, line) {
    val = process_value(rest)
    if (val == "") return
    if (classify(val) == "invalid")
        fail(sk, "value is not a valid Swift literal: " val)
    line = "    static let " sk " = " val
    if (last_comment != "") line = line " // " last_comment
    print line
}

function read_list_key(sk, rest,   parts, n, i, val, kind, kinds, vals, cmts, m, line) {
    n = unquoted_split(rest, parts)

    # Validate the whole list before emitting anything.
    m = 0
    for (i = 1; i <= n; i++) {
        val = process_value(parts[i])
        if (val == "") continue
        kind = classify(val)
        if (kind == "invalid")
            fail(sk, "list element is not a valid Swift literal: " val)
        m++
        vals[m] = val; kinds[m] = kind; cmts[m] = last_comment
        if (m > 1 && kind != kinds[1])
            fail(sk, "list mixes " kinds[1] " and " kind " (" vals[1] ", " val ") — " \
                     "a comma inside a |# comment splits the value; remove it")
    }

    print "    static let " sk " = ["
    for (i = 1; i <= m; i++) {
        line = "        " vals[i] ","
        if (cmts[i] != "") line = line " // " cmts[i]
        print line
    }
    print "    ]"
}

function camel_case(k,   parts, n, i, out) {
    n = split(tolower(k), parts, "_")
    out = parts[1]
    for (i = 2; i <= n; i++) {
        if (parts[i] == "") continue
        out = out toupper(substr(parts[i], 1, 1)) substr(parts[i], 2)
    }
    return out
}

{
    line = trim($0)
    if (line == "" || substr(line, 1, 1) == "#") next

    eq = index(line, "=")
    if (eq == 0) next

    key = trim(substr(line, 1, eq - 1))
    if (key == "") next
    rest = substr(line, eq + 1)

    sk = camel_case(key)
    if (has_unquoted_comma(rest)) read_list_key(sk, rest)
    else read_scalar_key(sk, rest)
}
AWK
)

read_key() {
    ENV_FILE="$ENV_FILE" ENV_LINENO="$2" awk "$AWK_READ_KEY" <<< "$1"
}

# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------

{
    echo "// swiftgen:ignore"
    echo "// swiftformat:ignore"
    echo "// Generated from $(basename "$ENV_FILE") — do not edit"
    echo ""
    echo "enum Secrets {"
    lineno=0
    while IFS= read -r line || [[ -n "$line" ]]; do
        lineno=$(( lineno + 1 ))
        read_key "$line" "$lineno"
    done < "$ENV_FILE"
    echo "}"
} > "$TMP"

if [[ -f "$OUT" ]] && cmp -s "$TMP" "$OUT"; then
    echo "note: ♻️  $(basename "$OUT") unchanged, kept existing file: $OUT"
else
    # rename(2): atomically replaces $OUT, so no separate rm is needed and the
    # compiler never observes a missing or half-written file. $TMP is always a
    # sibling of $OUT, hence same filesystem, hence a true rename rather than a
    # copy. -f skips the prompt if an existing $OUT is not writable (only the
    # directory's write permission actually matters to rename).
    mv -f "$TMP" "$OUT"
    echo "note: 🆕 generated $OUT from $ENV_FILE"
fi